### ISSUE TITLE
Support uv

### ISSUE THREAD

**Issue by zztkm** [sksat/setup-rye#48]
## 概要

Rye はデフォルトでは pip-tools を利用しますが、オプションで [uv](https://github.com/astral-sh/uv) を使うように設定することができるので、setup-rye で以下のように設定できるようにしたいです。

```yaml
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zztkm/setup-rye@use-uv
        with:
          use-uv: 'true'
```
